site:
  title: Arotna Leben
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://arotna.github.io/leben
  start_page: leben::index.adoc
content:
  edit_url: false
  sources:
  - url: .
    branches: HEAD
    edit_url: false



ui:
  bundle:
    url: https://github.com/arotna/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true

output:
  dir: ./docs

asciidoc:
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
    mod-loc: partial$
